#!/usr/bin/env python3
"""Slice hero_sheet.webp (2000x2000, 2 rows x 3 cols) into transparent PNG frames
and emit src/sprites.mjs with base64 data URIs."""
import base64, io, os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEET = os.path.join(ROOT, "assets", "hero_sheet.webp")
FRAMES_DIR = os.path.join(ROOT, "assets", "frames")
OUT_MJS = os.path.join(ROOT, "src", "sprites.mjs")

# (name, row, col) for the cells we use. Sheet grid is 2 rows x 3 cols.
CELLS = {
    "idle": (0, 0),   # front, fists up
    "runA": (1, 0),   # running
    "runB": (0, 1),   # side profile (2nd run frame)
    "jump": (1, 2),   # arms-up celebrate
}
WHITE_THRESHOLD = 232   # luminance above this becomes transparent
TARGET_H = 128          # exported frame height in px (downscaled in-game)

def slice_cell(sheet, row, col):
    w, h = sheet.size
    cw, ch = w // 3, h // 2
    return sheet.crop((col * cw, row * ch, (col + 1) * cw, (row + 1) * ch))

def whiten_to_alpha(img):
    img = img.convert("RGBA")
    px = img.load()
    w, h = img.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            lum = 0.299 * r + 0.587 * g + 0.114 * b
            if lum >= WHITE_THRESHOLD:
                px[x, y] = (r, g, b, 0)            # fully transparent
            elif lum >= WHITE_THRESHOLD - 28:
                fade = int(255 * (WHITE_THRESHOLD - lum) / 28)  # feather edge
                px[x, y] = (r, g, b, min(a, fade))
    return img

def autocrop(img):
    bbox = img.getbbox()
    return img.crop(bbox) if bbox else img

def scale_h(img, target_h):
    w, h = img.size
    nw = max(1, round(w * target_h / h))
    return img.resize((nw, target_h), Image.LANCZOS)

def main():
    os.makedirs(FRAMES_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(OUT_MJS), exist_ok=True)
    sheet = Image.open(SHEET).convert("RGB")
    entries = []
    for name, (row, col) in CELLS.items():
        cell = slice_cell(sheet, row, col)
        cell = whiten_to_alpha(cell)
        cell = autocrop(cell)
        cell = scale_h(cell, TARGET_H)
        png_path = os.path.join(FRAMES_DIR, f"{name}.png")
        cell.save(png_path)
        buf = io.BytesIO()
        cell.save(buf, format="PNG")
        b64 = base64.b64encode(buf.getvalue()).decode("ascii")
        entries.append((name, cell.size, f"data:image/png;base64,{b64}"))
        print(f"{name}: size={cell.size} bytes={len(b64)}")
    with open(OUT_MJS, "w") as f:
        f.write("// GENERATED by tools/slice_hero.py — do not edit by hand.\n")
        f.write("export const SPRITES = {\n")
        for name, size, uri in entries:
            f.write(f'  {name}: "{uri}",\n')
        f.write("};\n")
        f.write("export const SPRITE_NATURAL = {\n")
        for name, size, uri in entries:
            f.write(f'  {name}: {{ w: {size[0]}, h: {size[1]} }},\n')
        f.write("};\n")
    print(f"wrote {OUT_MJS}")

if __name__ == "__main__":
    main()
